package pair

import (
	"bytes"
	"crypto/rand"
	"encoding/hex"
	"strings"
	"testing"
)

// The index IS the protocol. Reordering the table changes what every past and
// future pairing displays, so the ends are pinned by value.
func TestTheEmojiTableIsIntactAndIndexedByPosition(t *testing.T) {
	if len(emojiTable) != 64 {
		t.Fatalf("the table has %d entries, want 64", len(emojiTable))
	}
	for i, e := range emojiTable {
		if e.Number != i {
			t.Errorf("entry %d carries number %d; the table is out of order", i, e.Number)
		}
		if e.Emoji == "" || e.Description == "" {
			t.Errorf("entry %d is incomplete: %+v", i, e)
		}
	}
	// Both ends, so a truncation or a reversal is caught.
	if emojiTable[0].Description != "Dog" {
		t.Errorf("entry 0 is %q, want Dog", emojiTable[0].Description)
	}
	if emojiTable[63].Description != "Pin" {
		t.Errorf("entry 63 is %q, want Pin", emojiTable[63].Description)
	}

	// Distinguishable at a glance: no two entries may share a description, or
	// a human comparing two screens is comparing the wrong thing.
	seen := make(map[string]int, 64)
	for i, e := range emojiTable {
		if prev, dup := seen[e.Description]; dup {
			t.Errorf("entries %d and %d are both %q", prev, i, e.Description)
		}
		seen[e.Description] = i
	}
}

// The same secret must produce the same seven emoji on both devices, every
// time. A SAS that is not deterministic is a mismatch a user reads as an
// attack.
func TestTheSameSecretAlwaysProducesTheSameSAS(t *testing.T) {
	secret := bytes.Repeat([]byte{0xa5}, 32)
	first, err := DeriveSAS(secret, testPairingID, testInitPub, testJoinPub)
	if err != nil {
		t.Fatalf("DeriveSAS: %v", err)
	}
	for i := 0; i < 20; i++ {
		again, err := DeriveSAS(secret, testPairingID, testInitPub, testJoinPub)
		if err != nil {
			t.Fatalf("DeriveSAS: %v", err)
		}
		if again.Indices != first.Indices {
			t.Fatalf("the same secret produced %v then %v", first.Indices, again.Indices)
		}
	}
}

// A different transcript must produce a different SAS -- that is the entire
// tripwire. If it did not, an injected fault would go unnoticed.
func TestADifferentSecretProducesADifferentSAS(t *testing.T) {
	a, err := DeriveSAS([]byte("one"), testPairingID, testInitPub, testJoinPub)
	if err != nil {
		t.Fatal(err)
	}
	b, err := DeriveSAS([]byte("two"), testPairingID, testInitPub, testJoinPub)
	if err != nil {
		t.Fatal(err)
	}
	if a.Indices == b.Indices {
		t.Fatal("two different secrets produced the same SAS")
	}

	// And a single flipped bit must change it, since an injected fault is
	// usually small.
	base := bytes.Repeat([]byte{0x00}, 32)
	flipped := append([]byte(nil), base...)
	flipped[31] ^= 0x01
	x, _ := DeriveSAS(base, testPairingID, testInitPub, testJoinPub)
	y, _ := DeriveSAS(flipped, testPairingID, testInitPub, testJoinPub)
	if x.Indices == y.Indices {
		t.Error("flipping one bit of the secret left the SAS unchanged")
	}
}

// Seven emoji from 64 is 42 bits, which is the number that matters: an attacker
// who has to produce a matching SAS is guessing one in four trillion, and the
// PAKE gives them one guess.
func TestEveryIndexIsInRangeAndTheSpaceIsUsed(t *testing.T) {
	seen := make(map[int]bool)
	for i := 0; i < 4000; i++ {
		secret := make([]byte, 32)
		if _, err := rand.Read(secret); err != nil {
			t.Fatal(err)
		}
		s, err := DeriveSAS(secret, testPairingID, testInitPub, testJoinPub)
		if err != nil {
			t.Fatal(err)
		}
		for _, idx := range s.Indices {
			if idx < 0 || idx > 63 {
				t.Fatalf("index %d is out of range", idx)
			}
			seen[idx] = true
		}
	}
	// 28000 draws over 64 values: anything short of all of them means the bit
	// extraction is masking part of the space away.
	if len(seen) != 64 {
		t.Errorf("only %d of 64 emoji are reachable; the bit extraction drops part of the range", len(seen))
	}
}

// A known secret with its expected indices, so a refactor of the bit shuffling
// has something to fail against. Generated by this implementation and pinned
// here deliberately: this is a regression pin, not an interoperability claim
// against Matrix, with which addy needs no wire compatibility.
func TestKnownSecretPinsTheBitExtraction(t *testing.T) {
	secret, err := hex.DecodeString(strings.Repeat("00", 32))
	if err != nil {
		t.Fatal(err)
	}
	s, err := DeriveSAS(secret, testPairingID, testInitPub, testJoinPub)
	if err != nil {
		t.Fatal(err)
	}
	t.Logf("all-zero secret -> %v %s (%s)", s.Indices, s.String(), s.Words())

	// Recompute the extraction independently, from the same six bytes, using a
	// different expression of the same rule. Two implementations of the shift
	// agreeing is worth more than one implementation agreeing with itself.
	var want [7]int
	{
		out, err := sasBytesForTest(secret, testPairingID, testInitPub, testJoinPub)
		if err != nil {
			t.Fatal(err)
		}
		var acc uint64
		for _, b := range out {
			acc = acc<<8 | uint64(b)
		}
		acc >>= 6 // drop the unused trailing six bits of the 48
		for i := 6; i >= 0; i-- {
			want[i] = int(acc & 0x3f)
			acc >>= 6
		}
	}
	if s.Indices != want {
		t.Errorf("indices = %v, independently computed %v", s.Indices, want)
	}
}

func TestAnEmptySecretIsRefused(t *testing.T) {
	if _, err := DeriveSAS(nil, testPairingID, testInitPub, testJoinPub); err == nil {
		t.Error("DeriveSAS accepted an empty secret")
	}
}

func TestWordsAreAvailableForReadingAloud(t *testing.T) {
	s, err := DeriveSAS([]byte("something"), testPairingID, testInitPub, testJoinPub)
	if err != nil {
		t.Fatal(err)
	}
	parts := strings.Split(s.Words(), ", ")
	if len(parts) != 7 {
		t.Errorf("Words() = %q, want seven comma-separated descriptions", s.Words())
	}
	// Several descriptions are two words, so a space separator would be
	// ambiguous to read aloud -- which is what Words() is for.
	for _, p := range parts {
		if p == "" {
			t.Errorf("Words() has an empty entry: %q", s.Words())
		}
	}
	if len([]rune(strings.ReplaceAll(s.String(), " ", ""))) == 0 {
		t.Error("String() produced nothing")
	}
}

var (
	testPairingID = bytes.Repeat([]byte{0x11}, 16)
	testInitPub   = bytes.Repeat([]byte{0x22}, 32)
	testJoinPub   = bytes.Repeat([]byte{0x33}, 32)
)

// The emoji bind the PAKE result to the two keys the devices are about to
// trust. Without that, the PAKE proves a shared password and nothing about who
// holds it, and the emoji confirm a fact nobody needed.
func TestTheSASBindsBothIdentityKeys(t *testing.T) {
	secret := bytes.Repeat([]byte{0x5a}, 32)

	base, err := DeriveSAS(secret, testPairingID, testInitPub, testJoinPub)
	if err != nil {
		t.Fatal(err)
	}
	other := bytes.Repeat([]byte{0x44}, 32)

	for name, got := range map[string]func() (SAS, error){
		"a different pairing id": func() (SAS, error) { return DeriveSAS(secret, other[:16], testInitPub, testJoinPub) },
		"a different initiator":  func() (SAS, error) { return DeriveSAS(secret, testPairingID, other, testJoinPub) },
		"a different joiner":     func() (SAS, error) { return DeriveSAS(secret, testPairingID, testInitPub, other) },
		"the two keys swapped":   func() (SAS, error) { return DeriveSAS(secret, testPairingID, testJoinPub, testInitPub) },
	} {
		s, err := got()
		if err != nil {
			t.Fatalf("%s: %v", name, err)
		}
		if s.Indices == base.Indices {
			t.Errorf("%s produced the same emoji", name)
		}
	}

	for name, args := range map[string][3][]byte{
		"no pairing id": {nil, testInitPub, testJoinPub},
		"no initiator":  {testPairingID, nil, testJoinPub},
		"no joiner":     {testPairingID, testInitPub, nil},
	} {
		if _, err := DeriveSAS(secret, args[0], args[1], args[2]); err == nil {
			t.Errorf("DeriveSAS accepted %s", name)
		}
	}
}
