import { app } from 'electron'
import { mkdir, rm } from 'node:fs/promises'
import { join } from 'node:path'
import type {
  InspectBodyPage,
  InspectCaInfo,
  InspectEnv,
  InspectFlow,
  InspectOpaqueTunnel,
  InspectPinnedHost,
  InspectSourceKind,
  InspectStartOptions,
  InspectStatus,
  InspectTrustStore
} from '../../shared/inspect'
import { INSPECT_DEFAULT_PASSTHROUGH, formatFingerprint } from '../../shared/inspect'
import { randomBytes } from 'node:crypto'
import { askNetdOnce } from './vpn/drivers/wireguard'
import { resolveBundled } from './vpn/binaries'
import { Supervisor } from './vpn/supervisor'
import type { SupervisorExit, SupervisorHandle } from './vpn/supervisor'
import { deleteSecret, getSecret, secretsAvailable, setSecret } from './secrets'
import {
  engageSystemProxy,
  installNssTrust,
  installSystemTrust,
  removeCertFile,
  removeNssTrust,
  removeSystemTrust,
  restoreSystemProxy,
  systemProxyEngaged,
  trustStatus,
  writeCertFile
} from './inspectTrust'
import type { TrustChangeResult, TrustContext } from './inspectTrust'

// The traffic inspector, from the main process's side.
//
// The proxy itself is `sidecar/netd`'s `inspect` mode; everything here is the
// part that cannot live in a Go process: where the certificate authority is
// kept between runs, what the renderer is allowed to hold, and what has to be
// put back when this stops.
//
// Three decisions shape the file:
//
//  1. **The CA private key is minted and stored here, and travels exactly
//     once.** It is generated by a throwaway sidecar through `askNetdOnce` —
//     which deliberately bypasses the supervisor's log ring — sealed with the
//     OS keychain by `secrets.ts`, and handed to the running sidecar on stdin
//     at start. It never reaches the renderer, never reaches a log, and never
//     reaches disk unsealed.
//
//  2. **The renderer never holds a body.** Flows arrive as headers, byte
//     counts and a capped preview. The full payload stays in the sidecar's
//     capture directory until someone opens that flow, which is the difference
//     between a window that survives a 200 MB download and one that does not.
//
//  3. **Stopping puts the machine back.** The system proxy is restored on
//     stop, on quit, and on the next launch after a crash. A user left with no
//     internet because OpsMaxx died at the wrong moment is the worst thing
//     this feature can do, and it is entirely preventable.

const CA_KEY_SECRET_ID = 'inspect.ca.key'
const CA_CERT_SECRET_ID = 'inspect.ca.cert'
const RUN_ID = 'inspect'

/** How many flows the main process keeps. The renderer is sent every flow as
 *  it happens and keeps its own list; this ring is what a newly-opened panel
 *  is backfilled from, so it is sized for "what happened recently", not for an
 *  audit trail. */
const FLOW_RING_MAX = 2_000

/** Timings, gathered so tests can shorten them. */
export const inspectTuning = {
  readinessTimeoutMs: 15_000,
  requestTimeoutMs: 20_000,
  gracefulTimeoutMs: 5_000,
  platform: null as NodeJS.Platform | null
}

function platformNow(): NodeJS.Platform {
  return inspectTuning.platform ?? process.platform
}

interface Pending {
  resolve: (v: unknown) => void
  reject: (e: Error) => void
  timer: NodeJS.Timeout
}

interface Run {
  handle: SupervisorHandle
  seq: number
  pending: Map<string, Pending>
  bindHost: string
  bindPort: number
  source: InspectSourceKind
  viaProfileId?: string
  captureBodies: boolean
  maxBodyBytes: number
  insecureUpstream: boolean
  spillDir: string
  /** Present only while the listener is off loopback. */
  credentials: { username: string; password: string } | null
  systemProxyEngaged: boolean
  stopping: boolean
}

let run: Run | null = null
let ca: InspectCaInfo | null = null
let passthrough: string[] = [...INSPECT_DEFAULT_PASSTHROUGH]
let pinned: InspectPinnedHost[] = []
let opaque: InspectOpaqueTunnel[] = []
let stoppedReason: string | undefined
const flows: InspectFlow[] = []
const flowIndex = new Map<string, InspectFlow>()

type Emitter = (channel: string, payload: unknown) => void
let emit: Emitter = () => {}

/** The renderer's window, injected by index.ts rather than imported, so this
 *  module stays testable without Electron's BrowserWindow. */
export function setInspectEmitter(fn: Emitter): void {
  emit = fn
}

/** Things that have to be told when capture stops.
 *
 *  The local terminal registers here because a shell it started during capture
 *  still has the proxy in its environment afterwards, and only it can say so.
 *  A registry rather than a direct call so the dependency stays one-way — this
 *  module knows something wants telling, not what. */
const stopListeners: (() => void)[] = []
export function onInspectStopped(fn: () => void): void {
  stopListeners.push(fn)
}

function announceStopped(): void {
  for (const fn of stopListeners) {
    // One listener throwing must not stop the others, and must never take the
    // teardown down with it.
    try {
      fn()
    } catch {
      /* a listener that cannot report is not a reason to fail a stop */
    }
  }
}

let supervisor: Supervisor | null = null
function sup(): Supervisor {
  // Its own run root, not the VPN's. The supervisor's reaper claims every
  // `*.pid` file under its root and claiming means killing, so sharing a root
  // between two consumers would have each one killing the other's process on
  // startup.
  supervisor ??= new Supervisor({ runRoot: join(app.getPath('userData'), 'inspect-run') })
  return supervisor
}

// ------------------------------------------------------------------ CA

/** The certificate authority, minted on first use and reused after that.
 *
 *  Reused rather than regenerated because the user installs it: a new
 *  authority every launch would mean a trust store filling with dead
 *  certificates and an inspector that stops working every time the app
 *  restarts. */
export async function inspectCa(): Promise<InspectCaInfo> {
  if (ca) return ca

  const storedCert = getSecret(CA_CERT_SECRET_ID)
  const storedKey = getSecret(CA_KEY_SECRET_ID)
  if (storedCert && storedKey) {
    const info = await describeCa(storedCert, true)
    // An expired authority is worse than none: every request fails with a
    // certificate error the user cannot act on. Replacing it silently is the
    // only outcome that leaves them with something that works, and the new
    // fingerprint in the UI is what tells them to install it again.
    if (info.notAfter * 1000 > Date.now()) {
      ca = info
      return info
    }
  }
  return mintCa()
}

/** Mints a new authority, replacing whatever was there. */
export async function inspectRegenerateCa(): Promise<InspectCaInfo> {
  // Trust for the old certificate is removed first: leaving a root in the
  // system store whose key no longer exists anywhere is exactly the kind of
  // litter a security tool must not create.
  if (ca) {
    const ctx = await trustContext()
    await removeSystemTrust(ctx).catch(() => undefined)
    await removeNssTrust().catch(() => undefined)
  }
  return mintCa()
}

async function mintCa(): Promise<InspectCaInfo> {
  const res = await askNetdOnce<{
    certPem?: unknown
    keyPem?: unknown
    fingerprint?: unknown
    notAfter?: unknown
    notBefore?: unknown
  }>('inspect.ca.generate', { commonName: 'OpsMaxx Traffic Inspector', validDays: 365 })

  if (typeof res?.certPem !== 'string' || typeof res?.keyPem !== 'string') {
    throw new Error('The sidecar did not return a certificate authority.')
  }
  // Sealed with the OS keychain, or not persisted at all. `secrets.ts` refuses
  // to write plaintext, and a root CA key in a plaintext file next to the
  // application is not a trade worth making for the convenience of surviving a
  // restart.
  const persisted = secretsAvailable() && setSecret(CA_KEY_SECRET_ID, res.keyPem)
  if (persisted) setSecret(CA_CERT_SECRET_ID, res.certPem)
  // Held in memory for this process either way, so a machine with no usable
  // keychain still gets a working inspector — it just mints a new authority
  // next launch, and `keyPersisted: false` is what tells the user why they
  // have to install the certificate again.
  if (!persisted) memoryCaKey = res.keyPem

  ca = await describeCa(res.certPem, persisted)
  return ca
}

/** Set only when the OS keychain refused to seal the key. Never written down. */
let memoryCaKey: string | null = null

function caKey(): string | null {
  return getSecret(CA_KEY_SECRET_ID) ?? memoryCaKey
}

async function describeCa(certPem: string, keyPersisted: boolean): Promise<InspectCaInfo> {
  const { X509Certificate } = await import('node:crypto')
  const cert = new X509Certificate(certPem)
  const fingerprint = cert.fingerprint256.replace(/:/g, '').toLowerCase()
  const certPath = await writeCertFile(certPem)
  return {
    certPem,
    fingerprint,
    fingerprintDisplay: formatFingerprint(fingerprint),
    notBefore: Math.floor(new Date(cert.validFrom).getTime() / 1000),
    notAfter: Math.floor(new Date(cert.validTo).getTime() / 1000),
    // Computed on every read rather than at mint time. The authority is
    // checked once when it is loaded, and an app left running for a year would
    // otherwise pass that check and then start failing every request with a
    // certificate error nothing on screen explained.
    expiresInSec: Math.floor((new Date(cert.validTo).getTime() - Date.now()) / 1000),
    commonName: cert.subject.split('\n').find((l) => l.startsWith('CN='))?.slice(3) ?? 'OpsMaxx Traffic Inspector',
    certPath,
    keyPersisted
  }
}

async function trustContext(): Promise<TrustContext> {
  const info = await inspectCa()
  return {
    platform: platformNow(),
    certPath: info.certPath,
    certPem: info.certPem,
    commonName: info.commonName
  }
}

// ------------------------------------------------------------------ control

function send<T>(method: string, params?: unknown): Promise<T> {
  const current = run
  if (!current) return Promise.reject(new Error('The traffic inspector is not running.'))
  const id = String(++current.seq)
  return new Promise<T>((resolve, reject) => {
    const timer = setTimeout(() => {
      current.pending.delete(id)
      reject(new Error(`The traffic inspector did not answer ${method} in time.`))
    }, inspectTuning.requestTimeoutMs)
    current.pending.set(id, { resolve: resolve as (v: unknown) => void, reject, timer })
    current.handle.write(`${JSON.stringify({ id, method, params })}\n`)
  })
}

function onLine(text: string): void {
  const line = text.trim()
  if (!line.startsWith('{')) return
  let msg: {
    id?: string
    ok?: boolean
    result?: unknown
    error?: { code?: string; message?: string }
    event?: string
    data?: Record<string, unknown>
  }
  try {
    msg = JSON.parse(line)
  } catch {
    // Never quoted back. A line we could not parse is a line that might still
    // be carrying whatever it failed to encode.
    return
  }

  if (typeof msg.id === 'string') {
    const pending = run?.pending.get(msg.id)
    if (!pending) return
    run?.pending.delete(msg.id)
    clearTimeout(pending.timer)
    if (msg.ok) pending.resolve(msg.result)
    else pending.reject(new Error(msg.error?.message ?? 'The traffic inspector reported an error.'))
    return
  }

  switch (msg.event) {
    case 'inspect.flow.begin':
      onFlowBegin(msg.data ?? {})
      return
    case 'inspect.flow.end':
      onFlowEnd(msg.data ?? {})
      return
    case 'inspect.pinned':
      onPinned(msg.data ?? {})
      return
    case 'inspect.opaque':
      onOpaque(msg.data ?? {})
      return
    case 'inspect.stopped':
      stoppedReason = String(msg.data?.reason ?? 'The traffic inspector stopped.')
      void stopInspect({ reason: stoppedReason })
      return
    default:
  }
}

function onFlowBegin(d: Record<string, unknown>): void {
  const id = String(d.flowId ?? '')
  if (!id) return
  const flow: InspectFlow = {
    id,
    startedAt: Number(d.startedAt ?? Date.now()),
    state: 'pending',
    request: {
      method: String(d.method ?? 'GET'),
      scheme: d.scheme === 'https' ? 'https' : 'http',
      host: String(d.host ?? ''),
      port: Number(d.port ?? 0),
      path: String(d.path ?? '/'),
      query: d.query ? String(d.query) : undefined,
      httpVersion: String(d.httpVersion ?? 'HTTP/1.1'),
      headers: Array.isArray(d.headers) ? (d.headers as InspectFlow['request']['headers']) : [],
      headersTruncated: d.headersTruncated === true
    }
  }
  flowIndex.set(id, flow)
  flows.push(flow)
  // Trimmed from the front rather than cleared: a panel opened after a busy
  // hour should show the last two thousand exchanges, not nothing.
  while (flows.length > FLOW_RING_MAX) {
    const dropped = flows.shift()
    if (dropped) flowIndex.delete(dropped.id)
  }
  emit('inspect:flow', flow)
}

function onFlowEnd(d: Record<string, unknown>): void {
  const id = String(d.flowId ?? '')
  const flow = flowIndex.get(id)
  if (!flow) return
  flow.endedAt = Number(d.endedAt ?? Date.now())
  flow.state = d.error ? 'failed' : 'complete'
  flow.status = typeof d.status === 'number' && d.status > 0 ? d.status : undefined
  flow.statusText = d.statusText ? String(d.statusText) : undefined
  flow.responseHeaders = Array.isArray(d.headers) ? (d.headers as InspectFlow['responseHeaders']) : undefined
  flow.contentType = d.contentType ? String(d.contentType) : undefined
  flow.requestBytes = Number(d.reqBodySize ?? 0)
  flow.responseBytes = Number(d.resBodySize ?? 0)
  flow.requestPreview = d.reqPreviewBase64 ? String(d.reqPreviewBase64) : undefined
  flow.responsePreview = d.resPreviewBase64 ? String(d.resPreviewBase64) : undefined
  flow.requestSpilled = d.reqSpilled === true
  flow.responseSpilled = d.resSpilled === true
  flow.requestTruncated = d.reqTruncated === true
  flow.responseTruncated = d.resTruncated === true
  flow.upgraded = d.upgraded === true
  flow.error = d.error ? String(d.error) : undefined
  emit('inspect:flow', flow)
}

function onPinned(d: Record<string, unknown>): void {
  const host = String(d.host ?? '')
  if (!host || pinned.some((p) => p.host === host)) return
  const entry: InspectPinnedHost = {
    host,
    attempts: Number(d.attempts ?? 0),
    at: Number(d.at ?? Date.now())
  }
  pinned.push(entry)
  emit('inspect:pinned', entry)
}

function onOpaque(d: Record<string, unknown>): void {
  const host = String(d.host ?? '')
  if (!host || opaque.some((o) => o.host === host)) return
  const entry: InspectOpaqueTunnel = { host, at: Number(d.at ?? Date.now()) }
  opaque.push(entry)
  emit('inspect:opaque', entry)
}

// ------------------------------------------------------------------ lifecycle

/** Reserves the single-inspector slot across the slow part of a start — minting
 *  a CA, spawning the sidecar, binding a port. `run` is only set at the end of
 *  all that, so without this two concurrent starts would each get past the
 *  check and race to spawn a second sidecar onto the same port. */
let starting: Promise<InspectStatus> | null = null

export async function startInspect(opts: InspectStartOptions = {}): Promise<InspectStatus> {
  if (run) return inspectStatus()
  if (starting) return starting
  starting = doStart(opts).finally(() => {
    starting = null
  })
  return starting
}

async function doStart(opts: InspectStartOptions): Promise<InspectStatus> {

  const info = await inspectCa()
  const key = caKey()
  if (!key) {
    throw new Error('The certificate authority key is unavailable. Regenerate the certificate to continue.')
  }

  const engine = await resolveBundled('opsmaxx-netd')
  if (engine.available === false) {
    throw new Error(engine.reason ?? 'The OpsMaxx network sidecar is not available in this build.')
  }

  const spillDir = join(app.getPath('userData'), 'inspect-capture')
  // Cleared on every start. Captured bodies are debugging material with a
  // session's lifetime, not an archive, and leaving the previous session's
  // request bodies on disk indefinitely is a promise nobody made.
  await rm(spillDir, { recursive: true, force: true }).catch(() => undefined)
  await mkdir(spillDir, { recursive: true, mode: 0o700 })

  const bindHost = opts.bindHost?.trim() || '127.0.0.1'
  // A listener anywhere but loopback is an open proxy for the network, and it
  // decrypts TLS. The sidecar refuses one without credentials; generating them
  // here means the user is never asked to invent a password for a thing they
  // did not know needed one.
  const needsCredentials = !isLoopbackBind(bindHost)
  const credentials = needsCredentials
    ? {
        username: opts.username?.trim() || 'opsmaxx',
        password: opts.password?.trim() || randomBytes(18).toString('base64url')
      }
    : null
  const captureBodies = opts.captureBodies !== false
  const maxBodyBytes = opts.maxBodyBytes ?? 8 * 1024 * 1024
  passthrough = normaliseHosts(opts.passthrough ?? passthrough)

  const handle = await sup().spawn({
    id: RUN_ID,
    noun: 'traffic inspector',
    command: engine.path ?? 'opsmaxx-netd',
    args: [],
    cwd: app.getPath('userData'),
    exeSha256: engine.sha256,
    // Belt and braces. Nothing echoes the key, but the supervisor captures
    // every line the child writes and the cost of listing it here is nothing.
    redact: [key],
    readiness: async (h) => {
      await new Promise<void>((resolve, reject) => {
        const timer = setTimeout(() => reject(new Error('The sidecar did not answer.')), inspectTuning.readinessTimeoutMs)
        const off = h.onLog((l) => {
          if (l.stream === 'stdout' && l.text.includes('"ok":true')) {
            clearTimeout(timer)
            off()
            resolve()
          }
        })
        h.write(`${JSON.stringify({ id: 'ready', method: 'ping' })}\n`)
      })
    },
    readinessTimeoutMs: inspectTuning.readinessTimeoutMs,
    gracefulStop: async (h) => {
      h.write(`${JSON.stringify({ id: 'bye', method: 'shutdown' })}\n`)
    },
    gracefulTimeoutMs: inspectTuning.gracefulTimeoutMs,
    // On failure only. A user who stopped it wanted it stopped; a crash while
    // the system proxy points at us is the case that needs recovering from.
    restart: 'on-failure',
    backoff: { baseMs: 500, maxMs: 10_000, jitter: 0.2 },
    crashLoop: { windowMs: 60_000, maxRestarts: 5 },
    logRing: { maxLines: 500, maxBytes: 256 * 1024 }
  })

  run = {
    handle,
    seq: 0,
    pending: new Map(),
    bindHost,
    bindPort: opts.bindPort ?? 0,
    source: opts.source ?? 'manual',
    viaProfileId: opts.viaProfileId,
    captureBodies,
    maxBodyBytes,
    insecureUpstream: opts.insecureUpstream === true,
    spillDir,
    credentials,
    systemProxyEngaged: false,
    stopping: false
  }
  stoppedReason = undefined

  handle.onLog((l) => {
    if (l.stream === 'stdout') onLine(l.text)
  })
  handle.onExit((e) => onExit(e))

  const started = await send<{ bindHost?: string; bindPort?: number }>('inspect.start', {
    bindHost,
    bindPort: opts.bindPort ?? 0,
    caCertPem: info.certPem,
    caKeyPem: key,
    passthrough,
    maxBodyBytes: captureBodies ? maxBodyBytes : -1,
    spillDir,
    upstreamCAsPem: opts.upstreamCAsPem,
    insecureUpstream: opts.insecureUpstream === true,
    username: credentials?.username,
    password: credentials?.password
  }).catch(async (e: unknown) => {
    // A sidecar that started but refused the configuration must not be left
    // running: it holds a port and does nothing.
    await stopInspect({ silent: true }).catch(() => undefined)
    throw e
  })

  run.bindHost = started.bindHost ?? bindHost
  run.bindPort = started.bindPort ?? 0

  if ((opts.source ?? 'manual') === 'system') {
    const engaged = await engageSystemProxy(run.bindHost, run.bindPort, platformNow())
    if (!engaged.ok) {
      await stopInspect({ silent: true }).catch(() => undefined)
      throw new Error(engaged.message ?? 'The system proxy settings could not be changed.')
    }
    run.systemProxyEngaged = true
  }

  const status = await inspectStatus()
  emit('inspect:status', status)
  return status
}

async function onExit(e: SupervisorExit): Promise<void> {
  if (!run || run.stopping) return
  if (e.restarting) {
    // The proxy is briefly gone while it restarts. Say so rather than letting
    // the panel claim everything is fine while requests fail.
    emit('inspect:status', await inspectStatus({ restarting: true }))
    return
  }
  stoppedReason = e.error?.message ?? 'The traffic inspector stopped unexpectedly.'
  await stopInspect({ reason: stoppedReason })
}

export async function stopInspect(
  opts: { silent?: boolean; reason?: string } = {}
): Promise<InspectStatus> {
  const current = run
  if (!current) {
    // Still worth doing: a crash may have left the machine pointed at a port
    // that no longer answers, and this is one of the three places that gets
    // fixed.
    await restoreSystemProxy().catch(() => undefined)
    return opts.silent ? bareStatus() : inspectStatus()
  }
  current.stopping = true
  run = null

  for (const [, p] of current.pending) {
    clearTimeout(p.timer)
    p.reject(new Error('The traffic inspector stopped.'))
  }
  current.pending.clear()

  // Restored before the process is killed, so a failure to kill still leaves
  // the machine's networking correct.
  if (current.systemProxyEngaged || (await systemProxyEngaged())) {
    await restoreSystemProxy().catch(() => undefined)
  }
  await current.handle.kill().catch(() => undefined)
  await rm(current.spillDir, { recursive: true, force: true }).catch(() => undefined)
  // After the proxy is actually down, so a shell told "capture stopped" cannot
  // then find it still answering.
  announceStopped()

  if (opts.reason) stoppedReason = opts.reason
  // A silent stop is the quit path and the failed-start path, and computing a
  // status means shelling out to `security` or `certutil` with a ten-second
  // timeout each. Nobody is going to read the answer, and on quit it would sit
  // inside the teardown window doing nothing but delaying the exit.
  if (opts.silent) return { ...(await bareStatus()) }
  const status = await inspectStatus()
  emit('inspect:status', status)
  return status
}

/** Status without the trust probes. Everything here is already in memory. */
async function bareStatus(): Promise<InspectStatus> {
  return {
    running: false,
    source: 'manual',
    ca: ca ?? undefined,
    trust: [],
    passthrough: [...passthrough],
    pinned: [...pinned],
    opaque: [...opaque],
    flows: flows.length,
    captureBodies: true,
    maxBodyBytes: 8 * 1024 * 1024,
    stoppedReason
  }
}

/** Called from app quit. Everything this feature changed outside itself is
 *  undone here, whether or not the inspector is still running. */
export async function disposeInspect(): Promise<void> {
  await stopInspect({ silent: true }).catch(() => undefined)
  await restoreSystemProxy().catch(() => undefined)
}

/** Called once at startup. If the previous run died between changing the
 *  machine's proxy settings and restoring them, this is what fixes it. */
export async function recoverInspect(): Promise<void> {
  await restoreSystemProxy().catch(() => undefined)
}

// ------------------------------------------------------------------ queries

export async function inspectStatus(extra: { restarting?: boolean } = {}): Promise<InspectStatus> {
  const info = ca ?? (await inspectCa().catch(() => null))
  const trust: InspectTrustStore[] = info
    ? await trustStatus({
        platform: platformNow(),
        certPath: info.certPath,
        certPem: info.certPem,
        commonName: info.commonName
      }).catch(() => [])
    : []
  const current = run
  return {
    running: !!current && !extra.restarting,
    listening: current ? { host: current.bindHost, port: current.bindPort } : undefined,
    lanExposed: current ? current.bindHost !== '127.0.0.1' && current.bindHost !== '::1' : undefined,
    source: current?.source ?? 'manual',
    viaProfileId: current?.viaProfileId,
    ca: info ?? undefined,
    trust,
    passthrough: [...passthrough],
    pinned: [...pinned],
    opaque: [...opaque],
    flows: flows.length,
    captureBodies: current?.captureBodies ?? true,
    maxBodyBytes: current?.maxBodyBytes ?? 8 * 1024 * 1024,
    insecureUpstream: current?.insecureUpstream ? true : undefined,
    requiresCredentials: current?.credentials ? true : undefined,
    stoppedReason
  }
}

/** Backfill for a panel that has just been opened. */
export function inspectFlows(limit = 500): InspectFlow[] {
  return flows.slice(-Math.max(1, Math.min(limit, FLOW_RING_MAX)))
}

export function clearInspectFlows(): void {
  flows.length = 0
  flowIndex.clear()
  emit('inspect:cleared', null)
}

export async function inspectBody(
  flowId: string,
  side: 'request' | 'response',
  offset = 0,
  limit = 64 * 1024
): Promise<InspectBodyPage> {
  return send<InspectBodyPage>('inspect.body', { flowId, side, offset, limit })
}

export async function setInspectPassthrough(hosts: string[]): Promise<InspectStatus> {
  passthrough = normaliseHosts(hosts)
  if (run) {
    await send('inspect.passthrough', { hosts: passthrough })
    // A host that is no longer intercepted is no longer failing to be
    // intercepted, so its pinning warning goes with it.
    pinned = pinned.filter((p) => !passthrough.includes(p.host))
    // Same for an opaque tunnel: the host is now let through untouched, so
    // the warning that it was being broken no longer describes anything.
    opaque = opaque.filter((o) => !passthrough.includes(hostWithoutPort(o.host)))
  }
  const status = await inspectStatus()
  emit('inspect:status', status)
  return status
}

/** The remedy offered when a host is reported as pinning. */
export async function allowPinnedHost(host: string): Promise<InspectStatus> {
  // Accepts either form: a pinning host arrives bare, an opaque tunnel arrives
  // as host:port, and a passthrough rule matches on the host alone.
  return setInspectPassthrough([...passthrough, hostWithoutPort(host)])
}

/** `host:port` down to `host`, which is what a passthrough rule matches on.
 *  IPv6 literals arrive bracketed, and splitting those on the last colon is
 *  the one way to get this wrong. */
export function hostWithoutPort(hostport: string): string {
  const h = hostport.trim()
  if (h.startsWith('[')) {
    const close = h.indexOf(']')
    return close > 0 ? h.slice(1, close) : h.slice(1)
  }
  // More than one colon and no brackets is a bare IPv6 address, which cannot
  // carry a port. Splitting on the last colon there would return half an
  // address, and a passthrough rule built from it would match nothing.
  if (h.split(':').length > 2) return h
  const colon = h.lastIndexOf(':')
  return colon > 0 ? h.slice(0, colon) : h
}

/** Whether a bind address is reachable only from this machine.
 *
 *  A hostname that is not an IP literal counts as remote: resolving it to
 *  decide a security question would mean trusting DNS for it. The same rule
 *  the sidecar applies, restated so the two cannot disagree about which
 *  listeners need a password. */
export function isLoopbackBind(host: string): boolean {
  const h = host.trim().toLowerCase().replace(/^\[|\]$/g, '')
  if (h === 'localhost' || h === '') return true
  if (h === '::1') return true
  if (h === '0.0.0.0' || h === '::') return false
  return /^127\.\d{1,3}\.\d{1,3}\.\d{1,3}$/.test(h)
}

function normaliseHosts(hosts: readonly string[]): string[] {
  const seen = new Set<string>()
  const out: string[] = []
  for (const raw of hosts) {
    const h = raw.trim().toLowerCase().replace(/\.$/, '')
    if (!h || seen.has(h)) continue
    seen.add(h)
    out.push(h)
  }
  return out.sort()
}

// ------------------------------------------------------------------ trust

export async function installInspectTrust(store: 'system' | 'nss'): Promise<TrustChangeResult> {
  const ctx = await trustContext()
  const res = store === 'nss' ? await installNssTrust(ctx) : await installSystemTrust(ctx)
  emit('inspect:status', await inspectStatus())
  return res
}

export async function removeInspectTrust(store: 'system' | 'nss'): Promise<TrustChangeResult> {
  const ctx = await trustContext()
  const res = store === 'nss' ? await removeNssTrust() : await removeSystemTrust(ctx)
  emit('inspect:status', await inspectStatus())
  return res
}

/** Removes every trace: trust, certificate, stored key, captured bodies. */
export async function forgetInspectCa(): Promise<void> {
  const ctx = await trustContext().catch(() => null)
  if (ctx) {
    await removeSystemTrust(ctx).catch(() => undefined)
    await removeNssTrust().catch(() => undefined)
  }
  deleteSecret(CA_KEY_SECRET_ID)
  deleteSecret(CA_CERT_SECRET_ID)
  memoryCaKey = null
  ca = null
  await removeCertFile()
  emit('inspect:status', await inspectStatus())
}

// ------------------------------------------------------------------ injection

/**
 * The environment that makes one process talk to the inspector and trust it.
 *
 * This is rung one of the whole feature and the only one that needs no
 * privilege, no system state and no cleanup: a terminal started with these
 * variables is intercepted, and one started without them is not.
 *
 * Applied to local terminals, and returned to the renderer so a person can
 * paste them into a shell of their own — including a remote one. It is
 * deliberately not pushed down an SSH channel: `sshd` drops every variable but
 * `LANG` and `LC_*` by default and reports nothing when it does, so that path
 * would look like it worked and capture nothing.
 *
 * The CA path variables are as important as the proxy ones. Node, Python's
 * `requests` and Go all carry their own trust store and ignore the system
 * one — which is the real reason most "this app pins its certificate" reports
 * are not about pinning at all.
 */
export function inspectEnv(): InspectEnv {
  const current = run
  if (!current || !ca) return {}
  // A listener bound to 0.0.0.0 is still reached from this machine over
  // loopback, and handing a process the literal 0.0.0.0 as a proxy address is
  // how a working proxy looks broken.
  const host = current.bindHost === '0.0.0.0' ? '127.0.0.1' : current.bindHost
  // Credentials go in the URL because that is the only place an environment
  // variable can carry them, and every client that reads HTTPS_PROXY
  // understands the form.
  const auth = current.credentials
    ? `${encodeURIComponent(current.credentials.username)}:${encodeURIComponent(current.credentials.password)}@`
    : ''
  const url = `http://${auth}${host}:${current.bindPort}`
  const certPath = ca.certPath
  return {
    HTTP_PROXY: url,
    HTTPS_PROXY: url,
    http_proxy: url,
    https_proxy: url,
    // Without this, every request to the machine's own services would be
    // bounced through the proxy — which usually works and occasionally
    // deadlocks, when the service being called is OpsMaxx itself.
    NO_PROXY: 'localhost,127.0.0.1,::1',
    no_proxy: 'localhost,127.0.0.1,::1',
    NODE_EXTRA_CA_CERTS: certPath,
    REQUESTS_CA_BUNDLE: certPath,
    SSL_CERT_FILE: certPath,
    CURL_CA_BUNDLE: certPath,
    // Go reads neither of the above. It reads this.
    GIT_SSL_CAINFO: certPath
  }
}

/** True when a new session should be given the inspector's environment. */
export function inspectInjectsSessions(): boolean {
  return !!run && run.source === 'sessions'
}
