import { app } from 'electron'
import { chmod, mkdir, readdir, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

// Scratch state for a running tunnel: pid files, engine control sockets, and
// the occasional ephemeral config an engine gives us no way to avoid writing.
//
// Everything here is 0700/0600 because the contents are not merely private,
// they are key material: an OpenVPN config carries an inline <key> block, and
// a default 0755 would leave that world-readable for as long as the tunnel is
// up.
const DIR_MODE = 0o700
const FILE_MODE = 0o600

/**
 * Run state lives under `userData`, never beside the binary.
 *
 * EVERYTHING UNDER THIS ROOT IS DELETED AT STARTUP. `sweepRunDirs([])` runs
 * with an empty keep list on every launch, by design: a directory left behind
 * by a SIGKILL would otherwise accumulate forever. Nothing that has to survive
 * a restart may live here — see `vpnStateRoot`, which exists because a
 * Tailscale node's identity was kept as a sibling of the run directories and
 * was therefore destroyed on every launch.
 * Portable mode
 *  redirects `userData` to a folder next to the executable (`portable.ts`),
 *  and the install directory itself may be read-only, so deriving the path
 *  from the app's own data directory is what makes both cases work (E60). */
export function vpnRunRoot(): string {
  // Guarded rather than assumed: this module is reachable from bundles that
  // are not running inside Electron, and throwing at module scope there would
  // take down an unrelated import.
  const base = typeof app?.getPath === 'function' ? app.getPath('userData') : tmpdir()
  return join(base, 'vpn-run')
}

/**
 * Durable per-profile state, for engines that have an identity to keep.
 *
 * A sibling of `vpnRunRoot()` and deliberately NOT inside it. A tsnet node's
 * directory holds its private key, and that key is the whole of what makes it
 * the SAME device on the tailnet next time — without it the node registers
 * afresh, the admin console fills with `opsmaxx`, `opsmaxx-1`, `opsmaxx-2`,
 * and every restart needs authorising again.
 *
 * It lived under the run root, which the startup sweep empties wholesale. The
 * two directories look alike and are opposites: one is scratch that must not
 * outlive the process, the other is identity that must.
 */
export function vpnStateRoot(): string {
  const base = typeof app?.getPath === 'function' ? app.getPath('userData') : tmpdir()
  return join(base, 'vpn-state')
}

/** A per-profile directory under the durable root, created 0700 because what
 *  engines keep there is key material. */
export async function createStateDir(profileId: string, root: string = vpnStateRoot()): Promise<string> {
  const dir = join(root, runIdSegment(profileId))
  await ensurePrivateDir(root)
  await ensurePrivateDir(dir)
  return dir
}

/** A run id reduced to one safe path segment. Run ids are generated by the
 *  manager, but they are the only part of these paths that is not a literal,
 *  so they are the only part that gets checked. */
export function runIdSegment(runId: string): string {
  const s = runId.replace(/[^A-Za-z0-9._-]/g, '_')
  if (!s || s === '.' || s === '..') {
    throw new Error(`Invalid VPN run id ${JSON.stringify(runId)}.`)
  }
  return s
}

// mkdir's `mode` is masked by the process umask, so a 0700 request under the
// common 0022 umask still lands as 0700 but under a 0000 umask lands as 0777.
// Setting the mode again afterwards is the only way to actually get it.
async function ensurePrivateDir(dir: string): Promise<void> {
  await mkdir(dir, { recursive: true, mode: DIR_MODE })
  // POSIX modes do not exist on Windows; failing to set one is not a reason
  // to refuse to start a tunnel there.
  await chmod(dir, DIR_MODE).catch(() => {})
}

export async function createRunDir(runId: string, root: string = vpnRunRoot()): Promise<string> {
  const dir = join(root, runIdSegment(runId))
  // The parent is hardened too: a 0700 run dir inside a 0755 root still leaks
  // the fact that a tunnel is running and which profile it belongs to.
  await ensurePrivateDir(root)
  await ensurePrivateDir(dir)
  return dir
}

export async function disposeRunDir(runId: string, root: string = vpnRunRoot()): Promise<void> {
  await rm(join(root, runIdSegment(runId)), { recursive: true, force: true }).catch(() => {})
}

/** Delete every run directory that no live run claims. Called at startup once
 *  the orphan reaper has decided which runs are still real, so a directory
 *  left behind by a SIGKILL does not accumulate forever (E48). */
export async function sweepRunDirs(liveIds: string[], root: string = vpnRunRoot()): Promise<void> {
  const keep = new Set(liveIds.map(runIdSegment))
  let entries
  try {
    entries = await readdir(root, { withFileTypes: true })
  } catch {
    return
  }
  for (const entry of entries) {
    if (!entry.isDirectory() || keep.has(entry.name)) continue
    await rm(join(root, entry.name), { recursive: true, force: true }).catch(() => {})
  }
}

/** Write a secret to a 0600 file inside a run directory. Used only where an
 *  engine leaves no alternative — stdin and the control channel are preferred
 *  everywhere they exist, because a file can be read by anything running as
 *  this user for as long as it is on disk. */
export async function writeSecretFile(
  runDir: string,
  name: string,
  body: string
): Promise<string> {
  const file = join(runDir, runIdSegment(name))
  // The mode argument only applies when the file is created, so an existing
  // file with looser permissions would keep them without the explicit chmod.
  await writeFile(file, body, { mode: FILE_MODE })
  await chmod(file, FILE_MODE).catch(() => {})
  return file
}
