import { lstat, readFile, readlink, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { firstOutputLine, VpnError } from '../errors'
import { readCommand } from '../netstate'
import type { NetApplyContext, PrivilegedResult } from '../netstate'
import { assertDnsSpec, isSplitDns, verificationFor } from './index'
import type { DnsManager, DnsSnapshot, DnsSpec, DnsVerification } from './index'

// Two entirely different worlds share one file name (E11).
//
// Under systemd-resolved, `/etc/resolv.conf` is a symlink into /run/systemd/
// and points at a stub at 127.0.0.53; writing to it either fails or is undone
// within seconds, and the real configuration is per-link state held by the
// daemon. Everywhere else the file *is* the configuration.
//
// Which one is in force is detected rather than assumed, and the answer is
// recorded in the snapshot so the revert takes the same branch even if the
// daemon was started or stopped while the tunnel was up.

const RESOLVECTL = 'resolvectl'
const INSTALL = 'install'
const LN = 'ln'
const RESOLV_CONF = '/etc/resolv.conf'
// The stub address systemd-resolved publishes. Its presence in a *static*
// resolv.conf is the case the symlink test alone would get wrong.
const RESOLVED_STUB = '127.0.0.53'

export interface LinuxDnsOptions {
  resolvConfPath?: string
}

/** `resolvectl status`, whole or per-link:
 *
 *    Link 5 (wg0)
 *        Current Scopes: DNS
 *    Current DNS Server: 10.0.0.1
 *           DNS Servers: 10.0.0.1 10.0.0.2
 *            DNS Domain: ~corp.example
 *
 *  Long server lists wrap onto continuation lines that carry no label, so a
 *  labelled line opens a list and unlabelled indented lines extend it.
 *
 *  A wrapped line is recognised by where it starts, not by what it contains.
 *  resolvectl right-aligns its labels and pads continuations out to the column
 *  the value started in, and an IPv6 hextet made only of the letters a-f
 *  (`dead::beef`, `cafe::1`) matches the label pattern perfectly — key `dead`,
 *  value `:beef`. Read as a label it dropped that server AND stopped the list,
 *  so the rest of a wrapped set vanished too; with `verify()` now rolling back
 *  on a missing server, that cosmetic parse miss became a tunnel teardown. */
export function parseResolvectlStatus(text: string): { servers: string[]; domains: string[] } {
  const servers: string[] = []
  const domains: string[] = []
  let collecting: 'servers' | 'domains' | null = null
  // The column the open list's values start in. Only consulted while
  // `collecting`, so its initial value never decides anything.
  let valueColumn = 0
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trimEnd()
    const indent = line.length - line.trimStart().length
    const wrapped = collecting !== null && line.trim() !== '' && indent >= valueColumn
    const kv = wrapped ? null : /^\s*([A-Za-z][A-Za-z ]*?)\s*:\s*(.*)$/.exec(line)
    if (kv) {
      valueColumn = kv[2] ? line.length - kv[2].length : line.indexOf(':') + 2
      const key = kv[1].trim().toLowerCase()
      const rest = kv[2].trim().split(/\s+/).filter(Boolean)
      if (key === 'dns servers' || key === 'current dns server') {
        for (const s of rest) if (!servers.includes(s)) servers.push(s)
        collecting = 'servers'
      } else if (key === 'dns domain') {
        for (const d of rest) if (!domains.includes(d)) domains.push(d)
        collecting = 'domains'
      } else {
        collecting = null
      }
      continue
    }
    if (!collecting || !/^\s+\S/.test(line)) {
      collecting = null
      continue
    }
    for (const token of line.trim().split(/\s+/).filter(Boolean)) {
      if (collecting === 'servers') {
        if (!servers.includes(token)) servers.push(token)
      } else if (!domains.includes(token)) domains.push(token)
    }
  }
  return { servers, domains }
}

/** `nameserver` lines of a resolv.conf, in order. */
export function parseResolvConf(text: string): { servers: string[]; searchDomains: string[] } {
  const servers: string[] = []
  const searchDomains: string[] = []
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.replace(/[#;].*$/, '').trim()
    if (!line) continue
    const tok = line.split(/\s+/)
    if (tok[0] === 'nameserver' && tok[1]) servers.push(tok[1])
    else if ((tok[0] === 'search' || tok[0] === 'domain') && tok.length > 1) {
      for (const d of tok.slice(1)) if (!searchDomains.includes(d)) searchDomains.push(d)
    }
  }
  return { servers, searchDomains }
}

export function renderResolvConf(spec: DnsSpec): string {
  const lines = [
    '# Generated by OpsMaxx while a VPN is connected.',
    '# The previous contents are held in this run\'s netstate.json and are put',
    '# back when the tunnel stops, including at the next start after a crash.'
  ]
  if (spec.searchDomains.length > 0) lines.push(`search ${spec.searchDomains.join(' ')}`)
  for (const s of spec.servers) lines.push(`nameserver ${s}`)
  return lines.join('\n') + '\n'
}

/** The `resolvectl domain` argument list. A bare suffix is a search domain; a
 *  `~`-prefixed one is routing-only — queries for it go to this link and no
 *  lookup is broadened by it. `~.` therefore means "this link resolves
 *  everything", which is how full-tunnel DNS is expressed (E12). */
export function domainArgs(spec: DnsSpec): string[] {
  const out = [...spec.searchDomains]
  if (isSplitDns(spec)) {
    for (const d of spec.splitDomains ?? []) out.push(`~${d.replace(/^\./, '')}`)
  } else {
    out.push('~.')
  }
  return out
}

export class LinuxDnsManager implements DnsManager {
  private lastCtx: NetApplyContext | null = null
  private readonly resolvConfPath: string

  constructor(opts: LinuxDnsOptions = {}) {
    this.resolvConfPath = opts.resolvConfPath ?? RESOLV_CONF
  }

  /** `read` distinguishes an empty resolv.conf from one that could not be
   *  opened, which the content alone cannot: both are `''`. Snapshot and
   *  backend detection are happy either way — they want whatever is there — but
   *  `verify()` has to tell "the file says nothing" (a real negative result)
   *  from "we never saw the file" (no result at all). */
  private async readResolvConf(): Promise<{
    content: string
    symlinkTarget: string | null
    read: boolean
  }> {
    let symlinkTarget: string | null = null
    try {
      if ((await lstat(this.resolvConfPath)).isSymbolicLink()) {
        symlinkTarget = await readlink(this.resolvConfPath)
      }
    } catch {
      symlinkTarget = null
    }
    let content = ''
    let read = true
    try {
      content = await readFile(this.resolvConfPath, 'utf8')
    } catch {
      content = ''
      read = false
    }
    return { content, symlinkTarget, read }
  }

  /** E11's detection, in the order that gets the awkward hosts right:
   *  resolvectl has to answer at all, and then either the file is a symlink
   *  into /run/systemd/ or it is a static file already pointing at the stub. */
  async detectBackend(): Promise<'resolvectl' | 'resolv.conf'> {
    const status = await readCommand(RESOLVECTL, ['status'])
    if (status.code !== 0) return 'resolv.conf'
    const { content, symlinkTarget } = await this.readResolvConf()
    if (symlinkTarget && symlinkTarget.includes('/run/systemd/')) return 'resolvectl'
    if (content.includes(RESOLVED_STUB)) return 'resolvectl'
    if (!content && !symlinkTarget) return 'resolvectl'
    return 'resolv.conf'
  }

  async snapshot(): Promise<DnsSnapshot> {
    const backend = await this.detectBackend()
    const file = await this.readResolvConf()
    const previous =
      backend === 'resolvectl'
        ? parseResolvectlStatus((await readCommand(RESOLVECTL, ['status'])).stdout).servers
        : parseResolvConf(file.content).servers
    return {
      platform: 'linux',
      capturedAt: Date.now(),
      runId: '',
      interfaceName: '',
      previous,
      backend,
      // Kept on both branches: if resolved is stopped while we are up, the
      // revert falls back to the file and needs its original contents. Spelled
      // out field by field so `read` — which is about this read, not about the
      // machine — never lands in the snapshot a later launch replays.
      resolvConf: { content: file.content, symlinkTarget: file.symlinkTarget }
    }
  }

  async apply(spec: DnsSpec, ctx: NetApplyContext): Promise<void> {
    assertDnsSpec(spec)
    this.lastCtx = ctx
    const backend = await this.detectBackend()
    if (backend === 'resolvectl') {
      const dns = await ctx.runPrivileged(RESOLVECTL, ['dns', spec.interfaceName, ...spec.servers])
      if (dns.code !== 0) throw failed(spec, RESOLVECTL, dns)
      const domains = domainArgs(spec)
      const dom = await ctx.runPrivileged(RESOLVECTL, ['domain', spec.interfaceName, ...domains])
      if (dom.code !== 0) throw failed(spec, RESOLVECTL, dom)
      return
    }
    // No stdin is assumed: the file is staged in the run directory, which is
    // 0700 and owned by us but readable by root, and copied into place by a
    // privileged command that takes only paths.
    const staged = join(ctx.runDir, 'resolv.conf')
    await writeFile(staged, renderResolvConf(spec), { mode: 0o644 })
    // `install` unlinks the destination first, so a resolv.conf that is a
    // symlink to somewhere else is replaced rather than written through.
    const res = await ctx.runPrivileged(INSTALL, ['-m', '0644', staged, this.resolvConfPath])
    if (res.code !== 0) throw failed(spec, INSTALL, res)
  }

  async revert(snapshot: DnsSnapshot, ctx?: NetApplyContext): Promise<void> {
    const use = ctx ?? this.lastCtx
    if (!use) return
    if (snapshot.backend === 'resolvectl') {
      // One command, idempotent, and it exits non-zero for a link that no
      // longer exists — which is the ordinary case after a crash.
      await use.runPrivileged(RESOLVECTL, ['revert', snapshot.interfaceName]).catch(() => {})
      return
    }
    const original = snapshot.resolvConf
    if (!original) return
    if (original.symlinkTarget) {
      await use.runPrivileged(LN, ['-sfn', original.symlinkTarget, this.resolvConfPath]).catch(() => {})
      return
    }
    // The run directory may already have been swept, so the restore file goes
    // wherever it can; both locations are ours and neither holds a secret.
    const staged = join(use.runDir || tmpdir(), 'resolv.conf.orig')
    try {
      await writeFile(staged, original.content, { mode: 0o644 })
    } catch {
      return
    }
    await use.runPrivileged(INSTALL, ['-m', '0644', staged, this.resolvConfPath]).catch(() => {})
  }

  async verify(spec: DnsSpec): Promise<DnsVerification> {
    const backend = await this.detectBackend()
    if (backend === 'resolvectl') {
      const res = await readCommand(RESOLVECTL, ['status', spec.interfaceName])
      // The command failing is not the same fact as the link having no servers.
      // A link with no DNS configured prints fine and parses to zero servers —
      // that is the `failed` below. This is resolvectl not answering at all, and
      // the previous wording ("reports nothing … did not take effect") read a
      // broken query as a broken tunnel and rolled a working one back.
      if (res.code !== 0) {
        return {
          status: 'skipped',
          actual: [],
          reason: `systemd-resolved could not be asked about ${spec.interfaceName}: ${res.stderr.trim().split(/\r?\n/)[0] || `${RESOLVECTL} exited ${res.code}`}`
        }
      }
      const parsed = parseResolvectlStatus(res.stdout)
      const check = verificationFor(spec, parsed.servers)
      if (check.status !== 'ok' || !isSplitDns(spec)) return check
      const want = (spec.splitDomains ?? []).map((d) => `~${d.replace(/^\./, '')}`.toLowerCase())
      const have = parsed.domains.map((d) => d.toLowerCase())
      const missing = want.filter((d) => !have.includes(d))
      if (missing.length === 0) return check
      return {
        status: 'failed',
        actual: parsed.servers,
        reason: `${spec.interfaceName} is not scoped to ${missing.join(', ')}, so the split DNS rule did not take effect.`
      }
    }
    const { content, read } = await this.readResolvConf()
    // On this branch the file IS the configuration, so an unopenable file is an
    // unreadable resolver state and not an empty one. `install` had already
    // reported success by the time we got here; nothing about a failed read says
    // it lied.
    if (!read) {
      return {
        status: 'skipped',
        actual: [],
        reason: `${this.resolvConfPath} could not be read, so the DNS change could not be confirmed either way.`
      }
    }
    return verificationFor(spec, parseResolvConf(content).servers)
  }
}

function failed(spec: DnsSpec, cmd: string, res: PrivilegedResult): VpnError {
  return new VpnError(
    'internal',
    `Could not set DNS for ${spec.interfaceName}: ${firstOutputLine(res, `${cmd} exited ${res.code}`)}`
  )
}
